- lib/src/arithmetics.rs
- lib/src/interpreter/plan.rs
Add boolean operations, remove some unnecessary complexity from `Plan` implementation,
add type checking operations for grounded types.
> Add type checking ops

- c/src/lib.rs
- lib/src/metta/text.rs
- lib/src/space/grounding.rs
Allow making changes in a shared atomspace non concurrently.
> Allow mutate shared atomspace

- c/src/metta.rs
- c/tests/CMakeLists.txt
- c/tests/check_atom.c
- c/tests/check_grounding_space.c
- c/tests/check_sexpr_space.c
- c/tests/check_types.c
- c/tests/test.c
- c/tests/test.h
- lib/src/metta/mod.rs
- lib/src/metta/types.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/CMakeLists.txt
- python/tests/common.py
- python/tests/test_atom.py
- python/tests/test_atom_type.py
This is not finished work, but PR to demonstrate current types related API which is present in Rust library and ported to the Python API.
> Types API demonstration

- c/src/metta.rs
- c/tests/check_sexpr_space.c
- lib/src/metta/text.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/common.py
- python/tests/test_examples.py
Split `SExprSpace` on `Tokenizer` and `SExprParser`. Add C and Python API. Implement Python `Atomese` using new API
> Parser api

- c/src/atom.rs
- c/src/metta.rs
- c/src/util.rs
- lib/src/common/plan.rs
- lib/src/metta/interpreter.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/test_atom.py
Add Python API to interpret expression step by step. Add API to print current plan.
> Interpret step-by-step api

- README.md
Minor setup instructions suggestions
> Instructions suggestions

- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/space/grounding.rs
> Fix conjunction queries

- README.md
- python/tests/scripts/d1_custom_types.metta
> Add comment in d1_custom_types.metta

- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/space/grounding.rs
> Fix incomplete bindings substitution in results of complex queries

- python/tests/common.py
- python/tests/scripts/b5_types_prelim.metta
- python/tests/scripts/c1_grounded_basic.metta
- python/tests/test_examples.py
> Atom argument for match + let* to fix test

- lib/src/metta/types.rs
> Support grounded types as dependent type's parameters

- CMakeLists.txt
- c/CMakeLists.txt
- python/CMakeLists.txt
> Use old cmake generator expresison syntax

- lib/src/metta/interpreter.rs
- python/tests/scripts/d2_higherfunc.metta
Return atom when type is generic.
> Hotfix for interpret atom as a type

- CMakeLists.txt
- c/src/atom.rs
- c/src/space.rs
- c/tests/check_grounding_space.c
- c/tests/check_types.c
- python/hyperon/atoms.py
- python/hyperonpy.cpp
- python/tests/CMakeLists.txt
- python/tests/test_bindings.py
> Replace bindings_t implementation in C and Python API #244

- python/hyperon/atoms.py
- python/hyperon/stdlib.py
- python/tests/test_atom.py
- python/tests/test_examples.py
> Add Char primary type

- lib/src/metta/runner/stdlib.rs
- python/tests/scripts/f1_imports.metta
> Fix redundant imports

- Dockerfile
- README.md
- c/Cargo.toml
- lib/Cargo.toml
- python/pyproject.toml
* Fix `README.md` and `Dockerfile` to use correct Pip version
* Update current version to 0.1.3
> Use correct Pip version

- .github/workflows/build.yml
- Dockerfile
- README.md
> Upgrade conan to 1.60.1 in order to support GCC 13

- lib/src/metta/text.rs
> Fix comment within expression when right before closing parenthesis

- lib/src/metta/interpreter.rs
Incorporating suggestion from @vsbogd here: https://github.com/trueagi-io/hyperon-experimental/pull/364#discussion_r1265793610
> Committed 4cc22d65d6c76ef14737550647142a838b74e7b3 to the wrong branch.  Oops.

- c/src/atom.rs
Changing atom_t internals from Box to *mut because cbindgen exports them differently on Arm.
https://github.com/trueagi-io/hyperon-experimental/issues/371
> Changing atom_t internals from Box to *mut

- python/sandbox/neurospace/neurospace.py
- python/sandbox/neurospace/test_nspace.metta
- python/tests/test_bindings.py
- python/tests/test_custom_space.py
* "Neurospace" example is extended with a nested query and multiple results returned by custom matching
* A unit test example from test_custom_space is tweaked to support multiple matching results as well to be less misleading
> Improvement of custom query examples

- python/sandbox/resolve/r.py
> dummy copy for MeTTa to fix resolve

- python/hyperon/metta.py
https://github.com/trueagi-io/hyperon-experimental/issues/417
> Print hyperson version

- c/src/metta.rs
- c/tests/check_runner.c
- lib/src/metta/runner/mod.rs
- python/hyperon/runner.py
- python/hyperonpy.cpp
- python/tests/test_metta.py
Plumbing errors from Runner & RunnerState interface through C & Python, to address https://github.com/trueagi-io/hyperon-experimental/issues/465
> Runner err accessors

- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/stdlib.rs
It was triggered by inability to write unit test for the #483 
I added this unit test as well.
> Implement boolean and, or, and not operations in Rust stdlib

- lib/src/atom/matcher.rs
Fix CI failure https://github.com/trueagi-io/hyperon-experimental/actions/runs/6875166920/job/18698225594
> Fix unit test to take into account global counter state

- .github/workflows/minimal.yml
- CMakeLists.txt
- c/CMakeLists.txt
It is indicative workflow. It doesn't prevent PR merge.
> Add minimal CI workflow

- python/sandbox/das_gate/dasgate.py
Fixed problem with variable substitution.
> fix for variable bindings

- lib/src/atom/matcher.rs
> Fix crash on retain all variables from single binding

- repl/src/interactive_helper.rs
- repl/src/metta_shim.rs
Small fix for the error when building REPL with --features minimal. Fix lifetime eliding warning.
> Fix REPL compiler error and warning

- .github/workflows/release-python.yml
> Exclude Python 3.12 from release

- Dockerfile
- README.md
This PR allows building docker from a local copy of the repo or from any git branch.
> Fix Dockerfile to allow building docker from a local copy of the repo

- c/src/atom.rs
- c/src/metta.rs
- lib/src/atom/mod.rs
Cosmetic refactoring of the `Grounded` traits in `atom/mod.rs`
> Cosmetic Grounded refactoring

- python/sandbox/test_gnd_conv.metta
> Change the comment in the sandbox test after #597

- python/tests/scripts/b3_direct.metta
This test ensures that when we evaluate an expression with two encounters of one variable, this variable gets the same binding.
> small test addition

- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
This is a possible approach to issue #354 
More discussion needed before merge.
> Adding "capture" operation.  Experimental approach to issue #354

- lib/src/metta/runner/stdlib_minimal.metta
- lib/src/metta/runner/stdlib_minimal.rs
Suggesting fix item 4 from https://github.com/trueagi-io/metta-lang-dev/issues/52#issue-2281069760
> Fix incorrect number of arguments type error constant

- .github/workflows/ci-auto.yml
- .github/workflows/ci-manual.yml
- .github/workflows/common.yml
- .github/workflows/docs.yaml
- .github/workflows/minimal.yml
- .github/workflows/release-python.yml
- CMakeLists.txt
- Dockerfile
- README.md
- c/CMakeLists.txt
- python/CMakeLists.txt
- python/install-hyperonc.sh
- python/pyproject.toml
- update Conan to 1.64
- update minimal CMake version to 1.19
- update actions versions
- add new OSes into job
- print additional information about environment
> Update manual CI job to run on macos-14 Apple Silicon

- README.md
https://github.com/trueagi-io/hyperon-experimental/issues/703
https://github.com/trueagi-io/hyperon-experimental/issues/584
> Python 3.12 is problematic with conan.

- lib/src/atom/matcher.rs
> Rename wiped variables in Bindings::retain

- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
Replace it by direct call to the CustomMatch::match_ if implemented.
Similar to https://github.com/trueagi-io/hyperon-experimental/pull/718/commits/57ecd884d6df623cbe006765f22d591e76ceab7c
> Remove GroundedAtom::match_ method

- Dockerfile
- README.md
> Fix docker build

- lib/src/metta/runner/stdlib_minimal.rs
> Uncomment tests which are not slow anymore

- lib/src/metta/interpreter_minimal.rs
- lib/src/metta/old_interpreter.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
> Fix nested variable operations

- README.md
Adding troubleshooting instruction to use before #432 is fixed
> Add instruction on troubleshooting REPL under Python virtual env

- python/sandbox/snet/snet_io.py
Subj. I've remade PR https://github.com/trueagi-io/hyperon-experimental/pull/765 to another branch.
> Generate service metta code but now atoms not text

- python/hyperon/exts/snet_io/snet_gate.py
- python/hyperon/exts/snet_io/test_snet_call.metta
So, I've added possibility to open channel and deposit funds via metta sdk. Like this:
`!(snet-sdk open_channel_and_deposit &generative-lms 100 10000)`
> open channel and deposit added

- python/hyperon/exts/das_gate/README.md
README for das_gate+metta setup is added. Readme is very brief, but might be sufficient.
> das_gate README added

- .github/workflows/docs.yaml
Version 2 will be removed on February 1st, 2025.
> Upgrade actions/cache version

- .github/workflows/ci-auto.yml
- .github/workflows/ci-manual.yml
- .github/workflows/common.yml
- .github/workflows/release.yml
ubuntu-20.04 is decommissioned by GitHub.
> Update ubuntu-20.04 to ubuntu-22.04

- python/hyperon/exts/agents/mock-chitchat/README.md
- python/hyperon/exts/agents/mock-chitchat/caller_langchain_singleuser_v1.py
- python/hyperon/exts/agents/mock-chitchat/caller_selector.py
- python/hyperon/exts/agents/mock-chitchat/caller_testmodel.py
- python/hyperon/exts/agents/mock-chitchat/chitchat_class.py
- python/hyperon/exts/agents/mock-chitchat/commands_parser.py
- python/hyperon/exts/agents/mock-chitchat/config.yaml
- python/hyperon/exts/agents/mock-chitchat/example_chitchat.py
- python/hyperon/exts/agents/mock-chitchat/example_lowlevel_environment.py
- python/hyperon/exts/agents/mock-chitchat/inline_animations_prompt.py
- python/hyperon/exts/agents/mock-chitchat/mock_auto_conv_history.py
- python/hyperon/exts/agents/mock-chitchat/mock_config.py
- python/hyperon/exts/agents/mock-chitchat/mock_image_handler.py
- python/hyperon/exts/agents/mock-chitchat/mock_messages.py
- python/hyperon/exts/agents/mock-chitchat/mock_ros2_node.py
- python/hyperon/exts/agents/mock-chitchat/mock_stt.py
- python/hyperon/exts/agents/mock-chitchat/mock_tts.py
- python/hyperon/exts/agents/mock-chitchat/mock_tts_interface_waci.py
- python/hyperon/exts/agents/mock-chitchat/mock_tts_say_with_cancel.py
- python/hyperon/exts/agents/mock-chitchat/stream_iterators.py
- python/hyperon/exts/agents/mock-chitchat/test_mock_stt.py
- python/hyperon/exts/agents/mock-chitchat/test_mock_tts_interface_waci.py
- python/hyperon/exts/agents/mock-chitchat/test_mock_tts_say_with_cancel.py
This PR adds mock environment for conversation agents, together with an example implementation of such an agent. 
@Necr0x0Der I've added it as a folder.  If it is better to add it as a library, when where should I put it?
> mock ros2 environment with mock chitchat

- lib/src/metta/runner/stdlib/mod.rs
Fixes #669 Issue is fixed by #863, this PR adds a unit test for the issue.
> Add the test for the tuple type check error

- lib/src/metta/runner/mod.rs
Fixes #481 Issue seems to be fixed in minimal MeTTa based interpreter, this PR is to fix behavior by adding tests.
@Necr0x0Der adding you to check whether test asserts the results you meant in https://github.com/trueagi-io/hyperon-experimental/issues/481#issuecomment-1894049126
> Add unit test for cases from issue #481

- lib/src/space/grounding/index/trie.rs
- lib/src/space/grounding/mod.rs
> Filter out results with variable loops

- lib/src/metta/runner/builtin_mods/fileio.rs
Should fix [issue 933](https://github.com/trueagi-io/hyperon-experimental/issues/933). Here is the manual run.
https://github.com/DaddyWesker/hyperon-experimental/actions/runs/15106288211
> Fix issue 933

- lib/src/metta/types.rs
> Return %Undefined% type for the tuple types when some atom inside has %Undefined% type

- lib/src/metta/text.rs
- repl/src/metta_shim.rs
> Fix REPL skips symbols from input line

- lib/src/metta/runner/modules/mod.rs
This test should check if call inside of metta code of some rust module actually happens if this rust module was imported.
> test for inner call while import added

- lib/src/metta/runner/modules/mod_names.rs
- lib/src/metta/runner/stdlib/stdlib.metta
> import! help updated

- hyperon-common/src/unique_string.rs
Otherwise tests interfere with each other.
> Run UniqueString tests in sequential mode
