trueagi-io/hyperon-experimental

- rust/src/arithmetics.rs
- rust/src/interpreter.rs
- rust/src/lib.rs
- rust/src/matcher.rs
Add MATCH and MATCH_NEXT operations to match a symbolic expression and iterate through match results until expression is successfully interpreted.
> Add interpreter for symbolic expressions

- lib/src/interpreter/matching.rs
- python/tests/CMakeLists.txt
- python/tests/test_minecraft.py
- python/tests/test_unification.py
It allows correctly interpret such examples as `(= (if True $then $else) $then)` without calculating value which matches with `$then` or `$else`. And thus it allows writing tests like MineCraft example.
> Make matching/reduction logic more complex to match before reduction

- README.md
- c/src/lib.rs
- lib/src/arithmetics.rs
- lib/src/common.rs
- lib/src/interpreter/matching.rs
- lib/src/interpreter/mod.rs
- lib/src/interpreter/subexpr.rs
- lib/src/lib.rs
- lib/src/tests.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/common.py
- python/tests/test_atom.py
- python/tests/test_examples.py
- python/tests/test_minecraft.py
Add old method calling example. Rework interpreter significantly to simplify the logic and almost pass sub-sum example without introducing unification. Simplify GroundedAtom.execute() API to allow implementing it in Python using common arguments and return values.
> Add old examples

- c/src/lib.rs
- lib/src/arithmetics.rs
- lib/src/interpreter/matching.rs
- lib/src/interpreter/mod.rs
- lib/src/interpreter/types.rs
- lib/src/lib.rs
Small improve of `GroundingSpace` passing move `Rc` inside `GroundingSpace`.
Add functions to check atom types using types information saved in atomspace. Add unit tests.
> Add type checking examples

- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/space/grounding.rs
Add ability to define custom matching for GroundedAtoms. Implement an example of custom matching for simple dictionary implementation in Rust.
> Custom matching

- c/src/atom.rs
- lib/src/atom/mod.rs
In order to allow static Atom instances we need Sync to be derived for
Atom and in turn require Sync for GroundedAtom implementations.
> Allow creation of the static instance of Atom

- c/src/space.rs
- c/tests/check_grounding_space.c
Variable name is properly converted to C string and guaranteed to be existing while callback is called. Before this fix the string which was passed to the caller was not zero ended.
> Fix unsafe passing variable name to the callback

- c/src/metta.rs
- c/tests/check_types.c
- lib/src/atom/subexpr.rs
- lib/src/metta/mod.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/test_atom_type.py
Rename `validate_expr` to `validate_atom`, allow validating single atoms. Allow atoms with undefined types as arguments. Add unit tests for type check functions.
> Allow passing atoms with undefined type as argument to the function expression

- c/tests/check_types.c
- lib/src/metta/text.rs
- lib/src/metta/types.rs
Analyze return type of the expression and check if it is require in `check_type`.
As a side effect of a spec implementation if atom has no specific type it can be matched against any type as it is required to use it as an argument of the typed function.
There is also a question about matching types of atoms by types of variables. I have added test on this and ignored it for the moment.
> Consider returned type as type of the expression

- lib/src/metta/types.rs
- python/tests/common.py
Rewrote type checking procedure to support dependent types. As a side effect all tuples are always validated because they always have the product type. There is a question should we explicitly forbid this and require types like `(Pair ...)` for representing tuples or allow validating any tuple. I also have small questions on some `asserts` in tests on dependent types, but it is simpler to check one by one.
> Add dependent types

- c/src/metta.rs
- c/src/space.rs
- lib/src/common/plan.rs
- lib/src/metta/interpreter.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
Add C to interpret expressions step by step.
What is not done:
- no API to print and explore intermediate step
- no Python friendly functions to use C API
> Add C and Python API to interpret expressions step by step

- c/src/metta.rs
- lib/src/atom/subexpr.rs
- lib/src/common/arithmetics.rs
- lib/src/common/plan.rs
- lib/src/metta/interpreter.rs
- python/tests/test_atom.py
Error state is added to the API of the plan library. New plan to select non error alternative is added. Interpreter code is reworked to keep only necessary steps and remove all steps which doesn't make sense from plan execution perspective. Interpreter code now is more compact and clear.
Next step: work on text plan representation to make plans more human readable.
> Simplify interpreter, remove non-clear steps from plan

- lib/src/atom/subexpr.rs
- lib/src/common/plan.rs
- lib/src/metta/interpreter.rs
- python/tests/test_atom.py
Make additional plans to improve text representation of the plan.
Example of the complex plan after refactoring:
```
interpret alternatives for (:? (= SocratesIsMortal (HumansAreMortal SocratesIsHuman))):
> interpret alternatives for (:= (= (:? SocratesIsMortal) (:? (HumansAreMortal SocratesIsHuman))) $t):
> interpret alternatives for (:? (HumansAreMortal SocratesIsHuman)):
> match (HumansAreMortal SocratesIsHuman) then interpret after reduction of (:= >(HumansAreMortal SocratesIsHuman)< $t) (or try reducting next arg in (:= >(HumansAreMortal SocratesIsHuman)< $t)) (or return [((:= (HumansAreMortal SocratesIsHuman) $t), {})]) then reduct next arg in (match &self >(:= (HumansAreMortal SocratesIsHuman) $t)< $t) (or return [((match &self (:= (HumansAreMortal SocratesIsHuman) $t) $t), {})])
- …
```
> Make plans more readable

- lib/src/common/collections.rs
- lib/src/common/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/space/grounding.rs
Add API to observe `GroundingSpace` state changes. Add `InterpreterContext` to encapsulate common interpreter context like space instance. Add interpreted expression cache into `InterpreterContext`. Keep interpretation result for the non-grounded expression in cache.
> Add interpreter cache

- c/src/lib.rs
- c/tests/test.c
- lib/Cargo.toml
- lib/src/atom/mod.rs
- lib/src/atom/subexpr.rs
- lib/src/common/arithmetics.rs
- lib/src/common/mod.rs
- lib/src/lib.rs
- lib/src/metta/examples/types.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/types.rs
- python/tests/test_examples.py
- python/tests/test_minecraft.py
- python/tests/test_minelogy.py
- python/tests/test_pln_tv.py
FYI, code does not require manual calling of `init_logger()` anymore. Removed this to make behavior more obvious. `RUST_LOG` environment variable should be used to configure logger behavior.
> Init logger on library load

- c/src/atom.rs
- c/tests/int_gnd.c
- c/tests/int_gnd.h
- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/common/arithmetics.rs
- lib/src/common/collections.rs
- lib/src/common/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/mod.rs
- lib/src/metta/text.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
Main change: add a field to keep type of the grounded atom inside `GroundedAtom` struct. Pass value to this field either automatically (using compile time Rust type knowledge) or manually. Use manual typing API to pass types for GroundedAtoms from Python library.
Minor changes: simplify Atom and GroundedAtom API.
> Add embedded types for GroundedAtom

- c/src/atom.rs
- lib/src/atom/mod.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/test_atom.py
Add API to pass grounded atom type into grounded atom constructor and to get atom type back from grounded atom.
Add an unit test to demonstrate approach.
> Python grounded types

- lib/src/metta/interpreter.rs
- python/tests/test_grounded_type.py
- python/tests/test_minelogy.py
Fixes comments for #95.
Added TODO and unit test for the undefined `OperationAtom` type.
Fixed behavior for the case where the interpreter returned empty result for an argument of the expression.
> Type based interpreter PR follow up

- python/tests/common.py
* `match` should have `Any` as output type, because it returns evaluated results.
* Fix `?`->`Any` for the argument of `println!`
It is necessary for numerous .metta scripts to output results correctly
> Fix types for print and match

- c/src/atom.rs
- c/src/metta.rs
- c/tests/check_grounding_space.c
- c/tests/check_sexpr_space.c
- lib/src/common/arithmetics.rs
- lib/src/metta/examples/types.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/mod.rs
- lib/src/metta/text.rs
- lib/src/metta/types.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/test_atom.py
- python/tests/test_common.py
- python/tests/test_examples.py
- python/tests/test_list_definition.py
Fixes #104
Resolve variables in parameterized types during type casting. Resolve variables when checking return type of the functions. Update algorithm of arguments interpretation to take into account type variables resolved in the previous arguments. 
Replace inheritance symbol `<` by `:<` to disambiguate with "lower than". 
Add unit tests for parameterized types in interpreter. Enable Python sorted list insert tests.
I have found that testing this changes in current API is quite difficult. I am going to raise PR as is for now to unblock work with polymorphic functions but as test coverage is poor I am not sure if it 100% works. I am going to improve test coverage may be with API changes in future PRs.
> Support parameterized types inside function signatures in interpreter

- lib/src/metta/interpreter.rs
- lib/src/metta/types.rs
Fixes #138 
Root cause of the issue is that when first atom inside expression doesn't have correct type (for instance `(S S`) in `((S S))` is incorrect constructor application to constructor) then `get_reducted_type()` returned empty list of types. So expressions with badly typed operator was not interpreted further.
This PR fixes this behavior returning `Undefined` type in such case.
> Return Undefined type when no type was found for operator atom

- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/space/grounding.rs
Fixes #127
This PR reworks pattern matcher to handle different tricky matches which were not processed before. I didn't implemented logic to substitute variables by their previous names because of reasons explained here: https://github.com/trueagi-io/hyperon-experimental/issues/127#issuecomment-1181645146
Particular cases which are handled now can be seen at the tests section of the `matcher.rs`.
> Fix expressions matching

- c/src/atom.rs
- c/src/space.rs
- c/src/util.rs
- lib/src/atom/mod.rs
- lib/src/metta/text.rs
Before this change two unique instances of the `VariableAtom` could still have same name. It affects C API call `grounding_space_query` because it returns `Bindings` using `VariableAtom.name()` string as a key. This PR prevents clashes.
It forbids using `#` symbol inside variable names assigned by user and uses this symbol to form unique variable name using `VariableAtom.id` field.
API also can be further changed by using `Atom` as a key in `Bindings`.
> Fix VariableAtom.name() function

- python/tests/common.py
- python/tests/test_examples.py
- python/tests/test_grounded_type.py
- python/tests/test_list_definition.py
- python/tests/test_minecraft.py
- python/tests/test_minelogy.py
- python/tests/test_nondeterm.py
- python/tests/test_pln_tv.py
- python/tests/test_unification.py
Use `metta.run` in unit-tests instead of `metta.interpret` and `metta.add_parse`. The reason for this is that we want a unified behavior for the process of interpretation and insertion of expressions, in particular, controllable by `pragma`'s (which are processed by `run`, e.g. for type-checking). This means that we need to get rid of interface functions, which bypass the runner.
> use  in unit tests

- c/src/metta.rs
- c/src/space.rs
- lib/src/common/arithmetics.rs
- lib/src/common/mod.rs
- lib/src/common/plan.rs
- lib/src/common/ptr.rs
- lib/src/metta/examples/types.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/text.rs
- lib/src/space/grounding.rs
- python/tests/test_atom.py
Refactoring of the code in before implementing Metta interpreting loop in Rust:
- add `SmartPtr` trait to make it possible passing both intrinsic references and smart pointers to the Metta interpreter;
- represent `GroundingSpace` as a smart pointer in C API.
> Metta interpreter in rust: preparations

- c/src/metta.rs
- lib/src/common/shared.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner.rs
- lib/src/metta/text.rs
- python/hyperon/__init__.py
- python/hyperonpy.cpp
- python/tests/test_metta.py
Implement `match`, `self`, `bind!`, `new-space`, `case`, `assert-equal`, `collapse`, `pragma!` in Rust.
> Add grounded symbols to Metta intepreter in Rust

- c/src/metta.rs
- lib/src/common/plan.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/mod.rs
Add error type parameter to StepResult, use (Atom, Atom) as a parameter. This is to add ability return type and other errors properly from the interpreter. It cannot be implemented right now as it breaks tests like `b5_types_prelim.metta` and I am going to continue this after moving runner into Rust completely.
> Add ability to return errornous atom and error symbol from interpreter

- lib/src/metta/mod.rs
- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/text.rs
- python/tests/test_metta.py
Add ability to override the token definition. Use this to keep Python values in Python MeTTa implementation.
> Implement arithmetics operations in Rust

- c/CMakeLists.txt
This is to be able adding unit tests into Rust implementation of Hyperon C API. This part of code is built only by cmake scripts and before this commit any unit test added into this code was not executed. Right now there are no unit tests but anyway we may want to add them for the utility classes which are written specifically for C API, like `CGrounded`.
> Enable running tests written in Rust C API implementation

- README.md
- lib/benches/grounding_space.rs
- lib/src/atom/mod.rs
- lib/src/common/assert.rs
- lib/src/common/collections.rs
- lib/src/common/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
- lib/tests/case.rs
- python/tests/scripts/b4_nondeterm.metta
- python/tests/test_common.py
- python/tests/test_examples.py
- python/tests/test_grounding_space.py
- python/tests/test_minelogy.py
- python/tests/test_pln_tv.py
- python/tests/test_run_metta.py
Add index to make search of patterns inside of `GroundingSpace` faster.
Add benchmark to measure time difference between searching in space with 10 atoms and space with 100 atoms.
Benchmark results before index is implemented:
```
Running benches/grounding_space.rs (target/release/deps/grounding_space-ce7d1e9199cc7107)
running 2 tests
test query_x10  ... bench:      13,899 ns/iter (+/- 156)
test query_x100 ... bench:     124,750 ns/iter (+/- 2,605)
```
Benchmark results after index is implemented:
```
Running benches/grounding_space.rs (target/release/deps/grounding_space-ce7d1e9199cc7107)
running 2 tests
test query_x10  ... bench:       3,808 ns/iter (+/- 121)
test query_x100 ... bench:       3,755 ns/iter (+/- 72)
```
One significant thing is not implemented yet: when value is removed …
> Improve space query performance

- c/src/space.rs
- lib/src/common/assert.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/space/grounding.rs
GroundingSpace::remove() changed indexes after removing leading element from GroundingSpace::content vector. Implementing more complex logic with GroundingSpace::content having free cells. Free cells are filled by adding new atoms. Add iter() method to iterate the GroundingSpace skipping free cells in content.
> Fix GroundingSpace::remove() method

- lib/src/atom/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/types.rs
- lib/tests/metta.rs
- python/tests/scripts/d2_higherfunc.metta
Interpret nested expression which return an operation. Make variables unique to fix type check in this case. Fix type of the lambda to make type-check successful.
> Interpret expression which return an operation

- c/src/metta.rs
- lib/src/common/shared.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
- lib/src/space/mod.rs
Introduce `Space` and `SpaceMut` traits, use `Space` as an input type restriction in interpreter and type checker API.
> Allow alternative space implementation

- lib/examples/custom_match.rs
- lib/src/atom/iter.rs
- lib/src/atom/matcher.rs
- lib/src/metta/types.rs
Replace custom matching function inside type checker with common `match_atoms()` implementation. Use custom grounded atom `UndefinedTypeMatching` to match undefined type with any other type. The change fixes issues related to not fully implemented matching in type checker.
> Use common match_atom() function in type matching

- lib/src/common/collections.rs
- lib/src/common/mod.rs
- lib/src/common/multitrie.rs
- lib/src/metta/runner/mod.rs
- lib/src/space/grounding.rs
Rename structures and functions, simplify code in order to make it more clear and prepare for the memory issue fix.
Resulting `MultiTrieNode` type is moved into the `hyperon::common::multitrie` module.
Next steps are:
- fix memory issue;
- document code;
> Refactoring of the atomspace index code

- lib/src/atom/matcher.rs
- lib/src/metta/types.rs
Add three unit tests in the ignored state to demonstrate the issue with `Bindings` API.
Change logs for the `check_types` function to demonstrate #188
> Unit tests to demonstrate the issue with Bindings API

- .github/workflows/ci.yml
- README.md
Python version 3.6 is not supported by the actual GitHub actions runners. The oldest runner is `ubuntu-20.04` and the oldest Python version is 3.7.
Makefiles still support 3.6 or later but this support is done on the best effort basis. Guarantees are given for the Python 3.7 and later.
> Ensure GitHub actions are executed with minimal supported Python version 3.7

- c/src/space.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/space/grounding.rs
- lib/src/space/mod.rs
Add default implementation for the Space::subst(), allowing to the implementers of the Space trait redefine it if it is needed. Remove GroundingSpace::subst() definition, reuse Space::subst().
> Add default Space::subst() implementation

- lib/src/atom/matcher.rs
There are several issues that need to be discussed.
1. This issue required changing many function signatures in matcher.rs to return `Vec<Bindings>` instead of  `bool` or `Option<Bindings>`.  Many of these functions are `Bindings` methods, so they formerly took `&mut self` as input.
Therefore some situations can cause a single `Bindings` input to create multiple `Bindings` outputs.  In this case, the `&mut self` pattern doesn't make sense.
In order to keeping the current code structure as much as possible, I changed the function signatures to take ownership of the input Bindings.  However this inherently leads to a strange API usage semantic.  See all the ugly `pop()` calls I added to the tests to keep them functioning as before.
For example: …
> Changes to handle multiple matching results.  Issue 257

- lib/src/common/multitrie.rs
- lib/src/common/shared.rs
- lib/src/space/grounding.rs
Fixes:
- memory issue for an atoms with large number of subexpressions;
- cleanup empty tree nodes after value is removed.
Documentation to the public API and overall index logic is added.
The idea is to have almost standard prefix tree with additional information about shortcuts to the ends of expressions. These shortcuts then can be used to continue search after matching the whole expression by wildcard key. `MultiTrieNode::add` function adds the key into the prefix tree, and setups shortcuts. `MultiTrieNode::remove` is rewritten via recursion to remove the child node when it becomes empty. `MultTrieNode::get` is only operation which requires an iterator through unexplored paths  so iterator is rewritten without macro.
> Fix index memory overflow

- lib/src/metta/runner/stdlib.rs
`trace!` is equivalent to Idris or Haskell Debug.Trace, that is, it prints a message to stderr and pass a value along.
For instance
```
!(trace! "Here?" 42)
```
prints to stderr
```
Here?
```
and returns
```
[42]
```
Note that the first argument does not need to be a string, which makes `trace!` actually quite capable on its own.  For instance
```
!(trace! ("Hello world!" (if True A B) 1 2 3) 42)
```
prints to stderr
```
(Hello world! A 1 2 3)
```
and returns
```
[42]
```
This does not completely remove the need for adding a `format` built-in and may be added later on if necessary.
> Add trace! built-in

- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
The variables in pattern part of `let` expressions are unique and visible only inside `let` expression. Variables from the matched part vice versa can be visible outside of `let` expression and thus should be moved into the template untouched.
Another part of the issue is the possible variable loop between internal variable in pattern and external variable in the matched atom. Current code doesn't match such patterns.
As a side change logging logic is improved to spot the loops inside bindings. Also `make_variables_unique()` function is rewritten using `Atom` iterator. It allows removing cloning in one usage at least.
This PR fixes the behavior and introduces Rust unit tests for the behavior.
It makes the following original example work correctly:
```
;; Knowledge
(→ P Q)
(→ Q R)
;; Rule …
```
> Fix (let ...) pattern/template var mapping

- python/hyperon/atoms.py
Fixes variable names like `$$t` in log.
> Remove dollar sign from the name of the type variable

- README.md
Add link to the MeTTa specifiction, MeTTa examples explained video, Hyperon wiki page. Add link to the contribution guide. Copying some general overview from Hyperon wiki page.
> Update header with links and information about MeTTa

- lib/src/metta/runner/stdlib.rs
One liner to make `!(+ (superpose (1 2 3)) 1)` pass a type check as expected.
> Fix SuperposeOp type to (-> %Undefined% %Undefined%)

- python/hyperon/atoms.py
- python/tests/test_atom.py
One liner fixes issue with displaying both number 42 and string "42" as 42.
> Use repr() to display Python grounded atoms in logs

- lib/src/metta/runner/stdlib.rs
- python/tests/scripts/b4_nondeterm.metta
This PR is to fix the following MeTTa script:
```
(: f (-> Number String))
!(superpose ((get-type (f 42)) (get-type (f "42"))))
```
which returns
```
[(Error ((get-type (f 42)) (get-type (f '42'))) NoValidAlternatives)]
```
This result shows interpreter cannot interpret the whole `superpose` expression because second argument `(get-type (f "42"))` returns empty result.
The PR adds unit tests to fix current behavior. `SuperposeOp` implementation is changed to interpret each sub-expression of expression independently and return combined result. In addition type for the `Error` is added into `stdlib` in order to prevent interpretation of the `Error` expression returned by `superpose`.
> Fix superpose to interpret arguments independently

- lib/Cargo.toml
- lib/src/atom/matcher.rs
- lib/src/metta/types.rs
API changes to address unfriendly API related to `Bindings` methods that returned `Vec<Bindings>`.  https://github.com/trueagi-io/hyperon-experimental/issues/257
> Updating matcher api to use BindingsSet object instead of Vec<Bindings>

- lib/benches/grounding_space.rs
- lib/src/atom/matcher.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
- lib/src/space/mod.rs
Changing some tests & documentation to call newer "_v2" functions instead of compatibility shims
Changing GroundingSpace & Space trait `query` method to return BindingsSet instead of Vec<Bindings>
Still remaining to migrate are: FFI Exports & Interpreter
> Low-impact changes to adopt new BindingsSet API

- lib/src/atom/mod.rs
- lib/src/metta/types.rs
If type from grounded atom is used as is its variables may clash with variables of another type.
> Make vars unique for the type returned by grounded atom

- c/tests/check_atom.c
- lib/src/atom/matcher.rs
- lib/src/metta/runner/stdlib.rs
Fixes #290. 
Get list of variables from atom and template and use them to replace variable equalities in `Bindings` by variable assignments. See https://github.com/trueagi-io/hyperon-experimental/issues/290#issuecomment-1546948623 for a description of logic behind the fix.
Also make displaying of `Bindings` more clear replacing `=` by `<-` to distinguish assignment and equalities. 
And fix the `panic!` in `matcher` when tracing is enabled for other modules only.
> Properly apply and return var equalities from let, let* and case

- lib/src/atom/matcher.rs
- lib/src/metta/interpreter.rs
This PR fixes the following example:
```
(= (get-ptrn) (-> (-> $a $b) (-> $a $c)))
!(let* (((-> $y $z) (get-ptrn))
((-> $u $v) (get-ptrn))
($z (-> $in Bool))
($u (-> Number String))
($y (-> Bool Number)))
$in)
```
which returns `[]` while it is expected to return `[Bool]`.
The root cause is that results of the `(get-ptrn)` call are cached. Thus in both calls inside `let*` the cache returns exactly same atom `(-> (-> $a $b) (-> $a $c))` and matching fails.
The fix applies the following rules for cached results. When atom is transformed from <input> to <result>:
- values of the variables which are present in input are kept with result;
- values of the variables which are present in <result> but not present in <input> are applied to the <result>;
- all other variables are cleaned up.
When …
> Correctly handle variables in results of the interpreter cache

- c/src/atom.rs
- lib/src/atom/iter.rs
- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/space/grounding.rs
This removes a code duplication and adds a standard way of filtering vars as it is a frequent operation.
Addresses https://github.com/trueagi-io/hyperon-experimental/pull/298#discussion_r1197338902
> Add filter_type() function into AtomIter to filter sub-atoms by types

- lib/src/atom/mod.rs
- lib/src/common/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/runner/stdlib.rs
Kind of experimental refactoring to reuse the variable mapping code which was written in three different places.
After writing this I think that may be the better way is to allow collecting `AtomIter` back into the atom, then one can use traditional `Iterator::map` instead of `Iterator::for_each(...)`. But it requires keeping the structure of the expression inside the iterated items, so I think we can do it in the future if we want.
> Add ReplacingMapper utility to reuse variable mapping code

- lib/Cargo.toml
- python/hyperonpy.cpp
PR fixes issue with logs absence in debug releases. The root cause is that `ctor` is not called when C API static library is built in debug configuration. I am calling `init_logger` manually from C library to fix it.
I opened https://github.com/mmastrac/rust-ctor/issues/280 to ask `ctor` author for help in investigation.
> Init logger in a Python API library

- lib/src/atom/matcher.rs
Quick fix for #313. Return None from Bindings::resolve() when variable is absent. Return variable itself when variable has no value.
> Return variable from Bindings::resolve() when no value is found

- c/src/atom.rs
- c/src/metta.rs
- c/src/util.rs
- c/tests/check_atom.c
- c/tests/check_space.c
- c/tests/util.c
- python/hyperonpy.cpp
Background:  @luketpeterson wrote:
>>  ## The `c_str_callback_t` pattern is less efficient than returning a malloced buffer.
>>
>> Regardless of the safer_ffi migration, I think we should eliminate the c_str_callback_t callback.
>>
>> My reasoning goes like this: The Rust &str & String types don’t include a trailing terminator character because the Rust types track a size.  The callback gets a non-owned read-only c_str argument, which the implementation created by allocating buffer and copying the string into the buffer, plus the terminator.  Then, the callback needs to do something with the string, and the most common thing is to allocate yet another buffer and copy the string again.
>>
>> We can save one of these copies by just returning an allocated buffer - not to mention making the …
> Changing c_str api to follow the snprintf() pattern

- lib/src/atom/matcher.rs
- lib/src/common/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/runner/stdlib.rs
Fix #323. When resulting atom contains variables which are absent in original atom they are replaced by unique instances. In such case variables in bindings should also be replaced.
What is not done:
This PR adds one more method into `Bindings` API. It is not published as a part of C API or Python API. Also I would like to minimize the number of such methods in `Bindings`. I am raising it because it is blocker and @ngeiswei asked doing it asap. Will add an issue on `Bindings` code polishing.
> Uniformly replace variables in bindings when returning cached result

- c/src/atom.rs
- c/src/space.rs
- lib/src/metta/types.rs
- python/hyperon/atoms.py
- python/hyperon/base.py
- python/hyperonpy.cpp
- python/tests/test_custom_space.py
- python/tests/test_grounding_space.py
This should address https://github.com/trueagi-io/hyperon-experimental/issues/328
I went back and forth about which level to build the bridge, but fundamentally I decided that it made the most sense to create separate translator functions at the C level because C doesn't have any kind of runtime introspection.
So I added:
`fn atom_gnd_for_space(space: *mut space_t) -> *mut atom_t` and
`fn atom_get_space(atom: *const atom_t) -> *const space_t`
But at the Python level, runtime type introspection is back, so I kept the original interface of:
`G(space)` and
`GroundedAtom::get_object()`
> Creating a pathway to wrap spaces in grounded atoms from C & Python

- c/src/atom.rs
- c/src/metta.rs
- python/hyperon/atoms.py
Originally, I had put the Python definition of ATOM_TYPE_GROUNDED_SPACE in atom.rs (precursor for the C API) and exported GroundedAtomType.SPACE to the Python API.
My thinking was to keep a separation from types returned by `atom_get_type()` and types returned by `atom_get_grounded_type()`.  However, it does make things a little more confusing.
Vitaly suggested putting the MeTTa types in the same place: https://github.com/trueagi-io/hyperon-experimental/pull/329#discussion_r1229642538
That is the purpose of this PR.
> Consolidating MeTTa type definitions in one place for Atom Types and Grounded Atom Types

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/common.yml
- .github/workflows/publish.yml
- c/CMakeLists.txt
- c/hyperonc-config.cmake.in
- python/.gitignore
- python/CMakeLists.txt
- python/hyperonpy.cpp
- python/setup.py
At the moment it is required to run `python3 -m pip install -e .[dev]` in order to update the `hyperonpy` module after some native code is changed. This PR changes the target directory for `hyperonpy` to `./python` which means that `hyperonpy` is automatically updated by `make` command.
Also this PR contains:
- add proper CMake package config for `hyperonc` library
- remove Python CMake installation because `pip` should be used instead
- stop uploading artifacts into GitHub internal storage as they are published to Release page
- rename GitHub Actions workflows and jobs to make them look better in GitHub UI
This PR is a step to `manylinux` package building.
> Automatically update hyperonpy module when Python hyperon package is installed in editable mode

- c/src/space.rs
- c/tests/check_space.c
- python/hyperon/__init__.py
- python/hyperon/atoms.py
- python/hyperon/base.py
- python/hyperon/runner.py
- python/hyperonpy.cpp
- python/tests/test_atom.py
- python/tests/test_atom_type.py
- python/tests/test_custom_space.py
- python/tests/test_grounding_space.py
1. Changed names to be more clear how different objects should be used. 
- PySpace -> Abstract
- Space Space -> SpaceRef
- GroundingSpace -> GroundingSpaceRef
2. Added API comments, briefly describing intended usage of objects and functions
3. Changed Space `query` return value to BindingsSet in both C and Python APIs
4. Added BindingsSet implementation for `__getitem__ ` Python BindingsSet, in order to be able to access the individual Bindings in the same list-of-dict format formerly returned by space.query()
5. Added `GroundingSpace` Python wrapper implementation, so basic GroundingSpace can be easily subclassed.
6. Rename hyperonpy trampoline functions to `_priv_` so users don’t get confused
> Python API usability issues.  Changes:

- .github/workflows/ci.yml
- lib/src/atom/matcher.rs
Fixes broken build, since upgrading toolchain to Rust 171.
> Simplifying bind_set! macro because Rust toolchain v. 171 changed the way declarative macros are parsed

- lib/src/metta/interpreter.rs
- python/hyperonpy.cpp
This addresses: https://github.com/trueagi-io/hyperon-experimental/pull/361#discussion_r1265670145
Removing superfluous `using type = T` in hyperonpy.cpp types
Also Fixing "suspicious deref" warning that started with new Rust tool chain
> Small cleanups

- c/src/atom.rs
- c/src/metta.rs
- c/src/space.rs
Issues from https://github.com/trueagi-io/hyperon-experimental/pull/367 code review
> Renaming to c_atom_vec_callback_t, and deleting unnecessary Borrow impl for atom_vec_t

- python/CMakeLists.txt
Select correct list of modules to search for CMake versions less than 3.18. `Development.Module` is supported from 3.18, on the other hand `Development` cannot be used for versions 3.18 and greater because it implies `Development.Embed` which in turn is absent in `cibuildwheel` environment.
> Fix Python searching procedure for CMake less than 3.18

- c/src/atom.rs
- c/tests/check_atom.c
- c/tests/check_space.c
- python/hyperon/atoms.py
- python/hyperonpy.cpp
- python/tests/test_bindings.py
Changes:
- Removing var_atom_t from the C API because it’s confusing
- Changing semantics of `c_var_binding_callback_t` (formerly `c_var_atom_callback_t`) so that the callback isn’t responsible for freeing atoms
- Renaming Python Bindings::add_var_bindings method to Bindings::add_var_binding, to be accurate and consistent with BindingsSet
- Adding convenience for BindingsSet::add_var_binding method to allow passing var atoms as strings
See https://github.com/trueagi-io/hyperon-experimental/issues/347
> API consistency changes around adding and traversing Bindings

- .github/workflows/release-python.yml
Fixes #382. Successful run https://github.com/vsbogd/hyperon-experimental/actions/runs/5713270546
> Fix install-hyperonc.sh arguments parsing issue on MacOSX

- doc/minimal-metta.md
- lib/src/atom/mod.rs
- lib/src/metta/interpreter2.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib2.rs
- lib/src/metta/types.rs
Add minimal MeTTa interpreter implementation in Rust (`interpreter2.rs`) and MeTTa interpreter written using the minimal MeTTa instructions (`stdlib2.rs`). One can switch to the new implementation editing [`metta/runner/mod.rs` lines 13-20](https://github.com/vsbogd/hyperon-experimental/blob/c394546eec90244084cd4e82f9ac0baa1c04e11d/lib/src/metta/runner/mod.rs#L12-L20).
As implementation is not finished yet and not fully integrated with a code in this mode about 3 old Rust unit tests fails. But all unit tests in `interpreter2.rs` and `stdlib2.rs` are expected to be green. Main change is inside `...2.rs` files, other code is almost not touched.
> Add initial minimal MeTTa implementation

- c/src/metta.rs
- python/hyperon/runner.py
- python/hyperonpy.cpp
In the case of hyperonc's `metta_t`, the `Rc<RefCell<T>>` (aka `Shared<T>`) pattern is unsound and obnoxious to work with.  Also it doesn't add much value.
The usage pattern for `metta_t` lead to a violation of RefCell's contract with `unsafe`.  (using `as_mut` to gain access to the `RefCell`'s inner value while demonstrably not having exclusive access)  Luckily it never caused any problems because the underlying `Metta` object was never changed.  But it was a bug waiting to happen if simple state was ever added to the Metta struct.
Also, The Metta (Rust type) never needs to be mutable because it is 100% internally mutable.  
Finally, the top-level runner has a simple life-cycle, unlike other objects where we rely on reference counting for deallocation and embed handles within other …
> Removing Rc<RefCell<T>> pattern from metta_t in hyperonc

- c/src/atom.rs
- c/src/space.rs
- c/tests/check_space.c
- python/hyperonpy.cpp
There are 3 C API fixes / improvements in this PR:
1. Adding C api test: test_space_nested_in_atom, which corresponds to they Python test `test_match_nested_grounding_space`, but without relying on Python.
2. Fixing oversight in C API in signature of `space_clone_handle()`, which I missed in the C API regularization pass a few weeks ago.
3. Adding `atom_vec_clone()` function, because it's convenient
> Fixing Optimized build when nesting a Space within an Atom, Adding new test for C API, etc.

- c/src/metta.rs
- c/tests/check_space.c
- doc/minimal-metta.md
- lib/Cargo.toml
- lib/benches/interpreter2.rs
- lib/src/atom/iter.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/interpreter2.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib2.rs
- python/hyperon/atoms.py
- python/hyperonpy.cpp
- python/tests/scripts/b5_types_prelim.metta
- python/tests/test_custom_space.py
- python/tests/test_run_metta.py
- repl/Cargo.toml
- repl/src/metta_shim.rs
Next batch of minimal MeTTa related fixes and changes:
- `minimal` feature is added to switch core library to the minimal MeTTa interpreter at compile time, one can run Rust unit tests using `cargo test --features minimal`
- minimal MeTTa's `match` is renamed to `unify` because previous `match` definition has different order of arguments and thus incompatible with new one, old `match` is added into minimal MeTTa standard library
- pattern matcher syntax extensions suggestions are added to the minimal MeTTa docs, docs are fixed
- `assert...`, `collapse`, `superpose`, `let` and `let*`, `case`, `match` and `pragma!` are added into minimal MeTTa standard library, some of them are added as grounded atoms because they require the working atomspace to evaluate arguments which is not implemented …
> Minimal MeTTa interpreter fixes and optimizations

- python/sandbox/das_gate/dasgate.py
- python/sandbox/das_gate/test_das.metta
This is a very sketchy and possibly not a canonical (in future) way to integrate DAS into MeTTa, but it might be valuable to have, because there are some potential issues on both sides.
> A sketch of DAS integration

- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib2.rs
- lib/tests/metta.rs
Quick fixes to keep tests passing
> Fixing build warnings and compile errors with minimal MeTTa

- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
Fixes https://github.com/trueagi-io/hyperon-experimental/issues/463.
> Load Rust grounded tokens before stdlib is loaded

- c/src/metta.rs
- docs/minimal-metta.md
- lib/src/atom/matcher.rs
- lib/src/metta/interpreter2.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib2.rs
- lib/tests/metta.rs
- python/hyperon/atoms.py
- python/hyperonpy.cpp
- python/tests/scripts/b5_types_prelim.metta
- python/tests/test_examples.py
Improving semantics of minimal MeTTa `chain` to make code more predictable. I didn't change the documentation yet because I am going to experiment with `eval/chain/return` further and then finalize the semantics. After adding `function/return` I managed to write MeTTa interpreter in minimal MeTTa which now passes almost all of the tests except:
- Minecraft related tests
- one test in minimal MeTTa Rust test pack
- `f1_import` test
List of changes:
Implement `function` and `return` symbols to allow coding function call flows. Make `chain` one-step operation, i.e. `chain` makes one step and inserts the result into a provided template. One can make `chain` work in a loop by: 
- using nested `chain`, then `chain` waits while nested `chain` returns result
- using nested `function`, then …
> Minimal interpreter: adding function/return and fix most of the tests

- lib/examples/sorted_list.rs
- lib/src/common/mod.rs
- lib/src/common/test_utils.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/interpreter2.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib2.rs
- lib/src/metta/types.rs
- python/hyperon/runner.py
This PR addresses the comment in `lib/metta/mod.rs` about the functions `metta_space` and `metta_atom`.
These functions are both moved into a test-only module called `common::test_utils`, and they are re-implemented in terms of a test-only runner.
NOTE: This PR sits on top of the extensive https://github.com/trueagi-io/hyperon-experimental/pull/450 PR, but actually has only one unique commit.
> Rework rust test functions & add stdlib comparison operators

- lib/src/metta/runner/stdlib.rs
A small fix for expressions like `(and True (let $x False $x))`
> fix let return type

- lib/Cargo.toml
- lib/src/metta/interpreter.rs
- python/tests/test_examples.py
This is fast fix for #242 to unblock PLN work. This code doesn't use `pragma!` because at the moment `pragma!` settings are not reachable from the interpreter. More elegant fixes described in the issue could be implemented after migration to the minimal MeTTa.
> Stop evaluation of expressions with variables as operations

- lib/src/metta/interpreter.rs
The simple example is calling grounded function to get time twice which returns same result.
> Stop caching result of the grounded operations

- README.md
- lib/Cargo.toml
Add comments to the features. Disable `variable_operation` feature by default. This is to change behaviour according to comments https://github.com/trueagi-io/hyperon-experimental/issues/242#issuecomment-1801136493 and https://github.com/trueagi-io/hyperon-experimental/issues/242#issuecomment-1803609289
> Disable variable_operation feature by default

- lib/src/metta/runner/stdlib.rs
#483 fixes the return type of `let`. #224 is an old similar issue. I don't see the reason not to fix the return type of `car-atom` / `cdr-atom` as well and close this old issue. It seems that this fix doesn't affect any test.
> fix return type of car/cdr-atom

- python/hyperon/runner.py
The reason for the change.
`MeTTa.load_py_module(self, mod_name)` in `load_py_module_from_mod_or_file` may fail even if `mod_name` is a relative path w.r.t. cwd. It happens if `mod_name` contains submodules, e.g. `(extend-py! A.B)`. This doesn't happen with `export PYTHONPATH="${PYTHONPATH}:."`. Thus, this change might not be required. However, since we have
```py
file_name = mod_name if ".py"
```
this means that we try to turn the module name into the file path. Turning `A.B` into `A.B.py` will not work in any case. If we turn it into `A/B.py` it will make more sense. It makes adding `.` to `PYTHONPATH` unnecessary.
> turn module path to file path in extend-py

- c/src/atom.rs
- lib/src/atom/matcher.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/interpreter2.rs
- lib/src/metta/types.rs
- python/hyperon/atoms.py
- python/hyperonpy.cpp
- python/tests/test_bindings.py
Remove resolve_and_remove because it makes logic of Bindings more complex and doesn't add anything valuable. It can be replaced by applying `Bindings` to the variable.
> Remove Bindings::resolve_and_remove method

- c/src/metta.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/text.rs
This PR adds a `Parser` trait, and changes `Metta::run` to accept any `impl Parser` instead of a `SExprParser`
I gathered this was a direction we want to go anyway, to allow additional syntaxes.
However my reason for needing this change right now is that the module loader needs a way to retain ownership of text before it's parsed, but keeping the text buffer along-side the parser would result in a self-referential object.  So this change lets me create an `OwningSExprParser` that owns the text it's parsing.
This is a tiny step towards merging the module system.
> Adding `Parser` trait

- lib/benches/interpreter2.rs
- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/metta/interpreter2.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/stdlib.metta
Use stack to represent state of the interpreter and eliminate atom deconstructing/constructing on each step. Make small performance related fixes in the interpreter written in MeTTa.
> Minimal interpreter performance fixes

- docs/minimal-metta.md
- lib/src/metta/interpreter2.rs
Adding description for:
- `function/return`
- `collapse-bind/superpose-bind`
Fixing previous text, explaining why `function` is introduced, more clearly describe the evaluation order of the interpreter and `chain`'s role.
> Document latest minimal MeTTa interpreter behavior

- lib/src/atom/matcher.rs
Observation: the `vars` HashSet that gets passed into `narrow_vars` starts to grow truly massive (1000 atoms for large recursive evaluations in minimal MeTTa), and a lot of time is wasted hashing and evaluating dependencies for each one.
This fix improves performance by ~5% for the test case here:
```
(= (TupleCount $tuple) (if (== $tuple ()) 0 (+ 1 (TupleCount (cdr-atom $tuple)))))
!(TupleCount (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32))
```
This is not a silver bullet by any measure, but I believe it never makes the situation worse.
> Speedup in narrow_vars in situations where the number of variables in the interpreter state gets huge

- lib/Cargo.toml
- lib/src/metta/interpreter2.rs
The "Immutable Set" pattern is essentially already already being used through a combination of `Rc` and cloning.
~20% speedup for chain-heavy tests.
Unfortunately not a silver bullet, but a worthwhile change given its low impact.
> Using im::HashSet for the `interpreter2::Variables` type

- lib/Cargo.toml
- lib/examples/custom_match.rs
- lib/src/atom/matcher.rs
- lib/src/common/holeyvec.rs
- lib/src/common/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/interpreter2.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/space/grounding.rs
Fixes #530. PR is a huge rework of `Bindings` implementation. New implementation is about 15% faster than previous one and logic is simpler. There are some minimal MeTTa tests which fails, the reason is the same as in https://github.com/trueagi-io/hyperon-experimental/pull/532#issuecomment-1884509626, so I am going to work on this in separate PR.
> Fix issue 530: rename variables to the same name when returning result from match

- python/hyperon/runner.py
This is fast fix to raise an error when erroneous extension is loaded:
```py
from hyperon.ext import register_atoms
@register_atoms
def my_atoms():
return {
'multi-sum': NonExistingAtom()
}
```
Right now error is too verbose because the whole stack is added in `hyperonpy.cpp`. To avoid it and return only message sent by user we need to introduce custom exception class to be able to distinguish it from other `RuntimeError`s.
> Raise RuntimeError when MeTTa extension is loaded with error

- c/src/metta.rs
- python/hyperon/atoms.py
- python/hyperonpy.cpp
- python/tests/test_atom.py
- python/tests/test_grounded_type.py
It is useful for the case when function without result is wrapped to the `GroundedAtom` and exported to MeTTa. In such case MeTTa expects instance of the unit type is returned (which is represented by empty expression `()`).
> Return unit if none in Python grounded functions when unwrap=True

- Cargo.toml
- README.md
- c/Cargo.toml
- c/src/metta.rs
- lib/Cargo.toml
- repl/Cargo.toml
Introducing virtual workspace Cargo.toml file allows reusing workspace configuration (version, dependencies) in all Rust subprojects.
> Add Cargo workspace configuration

- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib2.rs
- python/tests/scripts/f1_imports.metta
Hotfix for the #572 which can be used before modules system refactoring is merged and unblocks minimal MeTTa.
The idea of the fix is to add a temporal instance of atomspace which contains stdlib into an imported space and remove it after running imported code. Also needed to fix a test to not rely on an order of atoms returned. Last thing I have found that `get-atoms` returns non-unique instances of the variables and thus unification of `$x` and `(get-atoms $m)` is not possible when `&m` contains instances of `$x`.
> Import hotfix

- lib/src/space/mod.rs
Fixing build warning, on account of Rust 1.76 being more strict about pointer comparisons
> Fixing build warning, on account of Rust 1.76 being more strict about pointer comparisons

- lib/src/metta/runner/stdlib2.rs
The test `stdlib2::test_variable_defined_via_variabe` contains this code:
```
(= (myif T $y) $y)
(= (not F) T)
(= (a $z) (not (b $z)))
(= (b d) F)
!(eval (interpret (myif (a $x) $x) %Undefined% &self))
```
The problem is that the `not` operation is imported from stdlib/corelib in the modules branch.  So we get this error: `(Error (not F) not expects one boolean arguments)`
Would you be ok to change the test to be:
```
(= (myif T $y) $y)
(= (mynot F) T)
(= (a $z) (mynot (b $z)))
(= (b d) F)
!(eval (interpret (myif (a $x) $x) %Undefined% &self))
```
Or do you think the `not` operation shouldn't be imported?
Feel free to reject this PR if I've misunderstood the purpose of the test.
> Tweaking test in stdlib2, so it passes with new module import behavior

- Dockerfile
- README.md
- python/install-hyperonc.sh
- python/pyproject.toml
Conan version is upgraded to 1.62, Python 3.12 is excluded from supported versions because `subunit 1.4.0` dependency of `hyperonc` is incompatible with Python 3.12. This is hotfix to unblock Python packages release.
> Handle Python 3.12

- .github/workflows/release-python.yml
Manually install compatible version of Python into macosx-11 image to build dependencies using Conan (see https://github.com/trueagi-io/hyperon-experimental/issues/584).
> Manually install compatible Python version

- lib/src/metta/runner/stdlib.rs
In Python stdlib `==` has type `(-> $t $t Bool)` which makes interpreter to evaluate each argument before passing them to `==`. In Rust stdlib it was `(-> Atom Atom Bool)` which causes different behaviour.
This PR is to discuss and unify the behaviour.
> Make type of the EqualOp compatible with one from Python stdlib

- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib2.rs
`unify` doesn't behave as `match` in a case when space is matched with variable. `match` returns atoms from the space. `unify` assigns the space as a value for the variable.
> Replace match implemented via unify by the grounded version

- c/src/atom.rs
- c/src/metta.rs
- lib/src/atom/matcher.rs
- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
Squishing warnings that popped up with Rust 1.76.0
Mostly redundant imports on account of the language prelude including more traits
> Squishing warnings that popped up with Rust 1.76.0

- c/src/metta.rs
Fixes #599.  Change type from i8 to c_char.
> Make type of the buffer compatible with any platform

- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib2.rs
Adding `mod-space!` Op Atom, to access the space of a module, loading it if necessary
See https://github.com/trueagi-io/hyperon-experimental/issues/592
It's now possible to do this: `!(add-atom &new_space (mod-space! mod_name))`
Therefore, `!(add-atom &self (mod-space! stdlib))` adds the same atom(s) as `!(import! &self stdlib)`, but does not add any tokens.
For me the remaining question is whether we want to enshrine the "nested-sub-space" behavior into MeTTa semantics?  We could add a `merge-atoms` or similar operation, to make it clear we're bringing in all atoms from the source space, but the implementation in the present code would be identical to `add-atom`
> Adding `mod-space!` Op Atom, to access the space of a module, loading it if necessary

- python/hyperon/runner.py
When I designed the FsModuleFormat trait, I imagined it would always generate its own filesystem paths, so I didn't validate them in the `try_path` method.  However I later changed it so the user can supply explicit paths, e.g. through the `register-module!` operation.
So I added the necessary validation code so that the python format loader doesn't try (and fail) to load a non-python module.
> Fixing erroneous error in Python module format loader, when explicit path is specified

- python/hyperon/stdlib.py
- python/tests/test_stdlib.py
As per #621 , `stringToChars` is expected to produce `Expression`, but it result was wrapped into `ValueAtom` even in the unit test. While this could be done for some reason, it is most likely a bug, and `stringToChars` should really return `Expression`
> fix stringToChars

- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
This provides a friendlier way to accomplish the requirements of https://github.com/trueagi-io/hyperon-experimental/issues/592, getting the space access op for the src space to reduce before adding it to the dst space
> Adding `add-reduct` operation, to merge atoms from a src space into a dst

- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib2.rs
Executing `!(pragma! interpreter bare-minimal)` turns off interpreter written in minimal MeTTa and only minimal MeTTa interpreter is used.
I used "interpreter" keyword because I would like to try implementing switchable interpreter.
> Add pragma to turn off library interpreter written in minimal MeTTa

- lib/src/metta/text.rs
- repl/src/config_params.rs
- repl/src/repl.default.metta
Intended to address https://github.com/trueagi-io/hyperon-experimental/issues/619
> Adding support for parsing escape sequences in s-expression parser

- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
- lib/src/metta/text.rs
The rest of the fix for https://github.com/trueagi-io/hyperon-experimental/issues/634
> Flowing errors in tokenizer atom-constructor functions through to parser

- python/tests/scripts/f1_imports.metta
Tiny PR.  So we can close https://github.com/trueagi-io/hyperon-experimental/issues/466
> Fixing misleading obsolete comment in f1_imports.metta test

- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/modules/mod_names.rs
This PR addresses a degenerate case in `mod_name::normalize_name_path` that was preventing `!(mod-space top)` from resolving.
Not directly related, but a possible work-around for https://github.com/trueagi-io/hyperon-experimental/issues/354 for the doc-strings.
> Fix for !(mod-space top)

- python/sandbox/simple_import/example_01.metta
- python/sandbox/simple_import/example_01.py
- python/sandbox/simple_import/example_02_numpy.metta
- python/sandbox/simple_import/example_03_langchain.metta
- python/sandbox/simple_import/simple_import.py
Example of the implementation of simple but rather universal python import, which also adds support for keyword arguments for the call of python objects.  
Few notes:
* It is a simple implementation to demonstrate the idea.
* It should be implemented on the lower level to remove necessity of __unwrap. So it should be implemented on the basic level of integration of python objects. 
* Support for the call of methods for objects is done with the dirty “call_dot” operator. It should be done differently, for example fixing “call:” operator, or maybe better by simply parsing “.”
> Simple python import

- c/src/atom.rs
- c/src/metta.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/modules/catalog.rs
- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
- python/tests/test_include.metta
- python/tests/test_modules.py
This PR adds the `include` operation and associated changes so module loaders can make additional named resources available through a resource API.
I also included a fix for an occasional panic caused by the C API being misused, passing a NULL ptr to a function taking an array ptr, when a zero-sized array is desired.
> Adding module resource API and `include` operation

- python/hyperon/stdlib.py
- python/tests/test_stdlib.py
Probably not everything is right right now. Please check.
> Issue 655 solution

- lib/src/metta/runner/stdlib_minimal.metta
- python/tests/scripts/d4_type_prop.metta
Fix integration test d4_... to work after the change.
> Fix return operation type in minimal MeTTa stdlib

- c/src/metta.rs
- c/tests/check_runner.c
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/modules/mod_names.rs
- lib/src/metta/runner/stdlib.rs
- python/hyperon/runner.py
- python/tests/scripts/f1_imports.metta
This PR is a blocker for fixing the `relative_submodule_import_test`, and resolving several other issues.
It's a fairly substantial internal refactor to the module-loading process, but the only outward-facing change should be that modules are loaded as child modules of the module loading them, as opposed to loading at the top-level of the module namespace.
> Changing module loading logic so modules aren't merged into runner until loading is complete

- python/hyperon/__init__.py
- python/hyperon/_version.py
So, after recent changes to versioning, it seems that every time we're installing the hyperon file _version.py is being changed and adding it to gitignore won't change a thing since it is already in the repository. So, I've bypassed this problem and deleted the _version.py file. Please check.
> remove _version.py to prevent setuptools from failing

- .github/workflows/common.yml
- .github/workflows/docs.yaml
- .github/workflows/minimal.yml
- .github/workflows/release-python.yml
- docs/DEVELOPMENT.md
- python/install-hyperonc.sh
- python/pyproject.toml
- python/setup.py
Fix deprecation warnings from release job, opt out `musllinux` by default in `pyproject.toml`, fix issue with insufficient permissions when building using `macos-14` GitHub runner.
To install Python package for MacOSX Apple Silicon from test PyPi:
```
python3 -m pip install --index-url https://test.pypi.org/simple/ hyperon
```
Version `0.1.8.1` should be installed.
> Enable MacOSX Apple Silicon release

- lib/src/metta/runner/stdlib.rs
This is necessary for `(match (mod-space! stdlib) ...)` to work.
> fix the return type of modspace

- lib/src/metta/runner/stdlib.rs
In [PR](https://github.com/trueagi-io/hyperon-experimental/pull/684) the behavior of the `include` stdlib op was changed to potentially return an atom rather than the unit type.  I forgot to update the type signature, so that's what this PR does.
> Updating include op's type to match new behavior from prior PR

- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
- lib/tests/case.rs
I propose to get rid of `%void%` in `case` and replace it with `Empty`, since it is more consistent with minimal metta
> %void% -> Empty

- lib/src/atom/matcher.rs
- lib/src/metta/interpreter_minimal.rs
Extended list of variables only in operations which make stack deeper: `chain`, `function` and `collapse`. Cleaned up variables in a single place. Added an operation which applies and cleans up `Bindings` at once. Constructed finished frames using the same `Stack::finished` method.
This PR improves minimal MeTTa test performance on 20% and fixes issues in logic.
> Cleanup variable handling logic in minimal MeTTa interpreter

- python/hyperon/runner.py
Adds python `sitepackages` dirs as part of the default search path for hyperonpy
Hotfix for https://github.com/trueagi-io/hyperon-experimental/issues/699
> Hotfix for #699, Adding python `sitepackages` dirs as part of the default search path

- python/hyperon/atoms.py
Works similar to `py-atom`. If the object returned by Python code is callable, wrap it into `OperationAtom` instead of `ValueAtom`.
> Create OperationAtom if object is callable

- c/src/atom.rs
- lib/examples/custom_match.rs
- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/common/mod.rs
- lib/src/common/shared.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/interpreter_minimal.rs
- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
- lib/src/metta/runner/string.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
- lib/src/space/mod.rs
Separate custom matched grounded atoms and grounded atoms matched by equality to address https://github.com/trueagi-io/hyperon-experimental/pull/698/files#r1623809472
We cannot understand whether custom matching is implemented on a grounded atom because of lack of the specialization feature in stable Rust, so I compared two approaches:
- returning optional matching procedure `fn Grounded::get_match(&self) -> Option<Box<dyn Fn(&Atom) -> MatchResultsIter>>`
- and adding separate `fn Grounded::as_match(&self) -> Option<&dyn CustomMatch>`
- having separate flag `Grounded::has_custom_matching`
I chosen last one because:
- it seems more clean and logical to me having each separate customization aspect as a separate trait
- if specialization is available in a stable Rust we can automatize it
- …
> Separate custom matched grounded atoms and grounded atoms matched by equality

- lib/src/metta/interpreter_minimal.rs
Fix the case when chain should keep value of the variable calculated inside evaluated argument.
> Fix chain working with variables

- lib/src/atom/matcher.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/interpreter_minimal.rs
- lib/src/metta/runner/stdlib_minimal.rs
When call is made using variable as an actual parameter the variables equality is kept in stack frame bindings to track the value of the variable. At the same time as formal argument variables are local they are not added into the `Stack::vars` set. Thus it is possible that variable equality is wiped when returning from the next nested call. And if after this call value is assigned to the formal argument variable this value will not be assigned to the actual argument variable.
In the following example:
```
(= (bar) (function (return ())))
(= (foo $b) (function
; fake internal call which wipes variables equalities
(chain (eval (bar)) $_
(unify $b value
(return ())
(return (Error () \"Unexpected error\")) ))))");
!(chain (eval (foo $a)) $_ $a)
```
calling `(foo $a)` adds variable equality …
> Fix returning values through variables as actual parameters

- c/src/atom.rs
- lib/examples/custom_match.rs
- lib/src/atom/matcher.rs
- lib/src/atom/mod.rs
- lib/src/common/mod.rs
- lib/src/common/shared.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/interpreter_minimal.rs
- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/builtin_mods/catalog_mods.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
- lib/src/metta/runner/string.rs
- lib/src/metta/types.rs
- lib/src/space/grounding.rs
- lib/src/space/mod.rs
Straightforward change to separate `Grounded::execute` method in a same way `Grounded::match_` is separated. 
```
trait Grounded {
fn execute(...) -> ...;
}
```
by
```
trait Grounded {
as_execute(&self) -> Option<&dyn CustomExecute>
}
trait CustomExecute {
fn execute(...) -> ...;
}
```
Using such interface one can check whether atom is executable in advance without executing it.
Main change is inside `lib/src/atom/mod.rs` all other changes are moving old code according new interface.
> Move out executable

- .github/workflows/release-python.yml
Old release fails while installing dependencies on manylinux.
> Upgrade cibuildwheel version to 2.19.2

- c/src/atom.rs
- lib/src/atom/mod.rs
- python/hyperon/atoms.py
- python/hyperonpy.cpp
While working with MeTTa and DAS Gate, I faced the following situation: the same query that works perfectly with the built-in atom space, when executed using DAS, does not resolve some variables if a function is defined and called to match some condition.
For example:
```
[(parent of Paul = $y#40)]
[(parent of Paul = John)]
```
The first line is the output of a query on DAS. And the second one comes from the same query but using the built-in space.
The issue does not happen on DAS if the match is made without calling a function.
For example, this query fails (output shows a non-resolved variable):
```lisp
(= (get_parent_from_das $x) (match &das (Parent $y $x) $y))
!(parent of Paul = (get_parent_from_das Paul))
```
However, this `match` works perfectly (it shows the value):
```lisp
!(match …
```
> [BUGFIX] Fixing DAS vars resolution

- lib/src/metta/runner/mod.rs
- python/hyperon/runner.py
- python/tests/test_metta.py
It is required to migrate metta-motto code to the latest MeTTa interpreter (https://github.com/trueagi-io/hyperon-experimental/pull/728)
> Add Metta.evaluate_atom() method to the Python API

- c/src/atom.rs
- c/src/space.rs
- lib/src/atom/mod.rs
- python/hyperon/atoms.py
- python/hyperon/exts/das_gate/dasgate.py
- python/hyperonpy.cpp
- python/sandbox/sql_space/sql_space.py
- python/tests/test_bindings.py
Follow up #729. This PR contains two main parts:
1. Remove `Bindings` and `BindingsSet` method variants which work with strings instead of variables. This is technical debt after introducing full functional Python API for the variable bindings.
2. Add `VariableAtom::parse_name()` method to parse `VariableAtom::name()` method results into Rust and Python API. This is a technical debt after introducing unique variable instances.
New methods are used to fix DAS gate variable conversion logic.
@besSveta please check this change doesn't break `sql_space.py` logic.
@angeloprobst FYI.
> Improve variable related API

- .dockerignore
- .gitignore
- CMakeLists.txt
- Cargo.toml
- Dockerfile
- README.md
- c/.gitignore
- docs/CONTRIBUTING.md
- python/.gitignore
- python/pyproject.toml
- repl/Cargo.toml
Use minimal Python 3.10 image based on Debian `python:3.10-slim-bookworm` as a starting point.
Use multi-stage build to start from clean environment after building is finished. In addition debug information is stripped from Rust binaries. Resulting image's size is about 180 Mb which is 50Mb greater than the Python runtime size.
Rust executable file is renamed to `metta-rust` and Python executable is aliased by `metta-py` in order to remove name conflict between them. Documentation is updated.
`.dockerignore` file is added in order to make Docker builds faster. `.dockerfile` is a soft-link to the `/.gitignore` which now keeps all files ignored by Git in repo. Welcome message is added to the container to show environment version and explain basic commands.
> Minimize docker image size

- c/src/metta.rs
- python/hyperon/runner.py
- python/hyperonpy.cpp
- python/tests/test_extend.py
The `test_error_pyext` test in the `test_extend.py` was aborting due to an (intentional) uncaught exception from Python.
This PR fixes it by implementing the missing error pathway from C loader function, and then using that pathway in hyperonpy
> Propagating python errors in loader through to MeTTa

- .github/workflows/release.yml
- repl/Cargo.toml
- repl/src/metta_shim.rs
Fix version checking procedure in REPL to not hardcode the required version (@luketpeterson please review).
Add Docker image building and publishing step into release workflow.
Separate test and production environments for PyPi and DockerHub to be able approve each step separately.
> Add Dockerhub publishing step to the release GitHub Action workflow

- lib/src/metta/interpreter_minimal.rs
- lib/src/metta/runner/stdlib_minimal.metta
- lib/src/metta/runner/stdlib_minimal.rs
Rename `apply` to `atom-subst` in order to make name more unique and better reflect nature of the function.
Fix case of passing `Error` expressions as a function parameters. In particular:
```
! (get-type Error) ; (-> Atom Atom ErrorType)
! (get-metatype Error) ; Symbol
! (get-type (Error Foo Boo)) ; ErrorType
! (Error (+ 1 2) (+ 1 +)) ; (Error (+ 1 2) (+ 1 +))
```
> Fix minimal and old_interpreter MeTTa incompatibilities

- Dockerfile
- README.md
- python/tests/scripts/f1_imports.metta
- repl/Cargo.toml
- repl/src/metta_shim.rs
> Remove no_python feature, make it work by default

- README.md
- c/conanfile.txt
- python/pyproject.toml
Fixes #584 Turn off using `subunit` in `libcheck` to fix incompatibility
> Fix python 3.12 incompatibility

- .github/workflows/ci-auto.yml
- .github/workflows/ci-manual.yml
- .github/workflows/common.yml
- .github/workflows/old_interpreter.yml
- .gitignore
- CMakeLists.txt
- Dockerfile
- README.md
- c/CMakeLists.txt
- c/conanfile.txt
- c/tests/CMakeLists.txt
- conan_provider.cmake
- python/CMakeLists.txt
- python/conanfile.txt
- python/install-hyperonc.sh
- python/pyproject.toml
- python/setup.py
Fixes #421, also fixes release scripts to support Python 3.12 which is a part of #584.
New build configs are incompatible with Conan 1.64, thus upgrade to Conan 2 is required to build the project.
CMake update is also required because [cmake-conan](https://github.com/conan-io/cmake-conan) is not compatible with CMake <3.24.
Release test results https://github.com/vsbogd/hyperon-experimental/actions/runs/10169067698
> Migrate to Conan2

- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.rs
- python/hyperon/stdlib.py
- python/tests/test_stdlib.py
Make string a token which has double quote as a first and a last characters don't matter what is inside. Otherwise strings like `"te\"st"` are parsed as symbols because they cannot be recognized by regex `"[^"]*"`.
> Fix string token definition in stdlib

- Cargo.toml
- lib/src/metta/runner/stdlib_minimal.rs
- python/hyperon/stdlib.py
- python/tests/test_stdlib.py
Fix #780 allow recognizing `\n` by `.` inside regex using flag `s`
> Fix newline

- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.metta
- lib/src/metta/runner/stdlib_minimal.rs
Fixes #760 
Also removes interpreter from the functions implementations.
> Fix unique

- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.metta
- lib/src/metta/runner/stdlib_minimal.rs
Clean version without weird commits from other branches, with tests and documentation.
> index-atom final version, documentation and tests added

- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.metta
- lib/src/metta/runner/stdlib_minimal.rs
I've added random-float and random-int to stdlib. Also I've added documentation and tests. Though I'm not sure how to test anything except error since number is random. Any possible way?
Usage is simple:
!(random-int 0 5)
!(random-float 0 10)
> random-float and random-int added

- python/hyperon/atoms.py
- python/hyperonpy.cpp
- python/tests/test_grounded_type.py
Fix names of the functions inside pybind11 macro stub.
@DaddyWesker should fix example from #791
> Fix native interface of the Python serializer

- lib/src/metta/runner/stdlib.metta
- lib/src/metta/runner/stdlib.rs
- lib/src/metta/runner/stdlib_minimal.metta
- lib/src/metta/runner/stdlib_minimal.rs
So, I've added three functions: size-atom, max-atom and min-atom. Works as supposed by the name:
!(size-atom (5 4 3))
[3]
!(max-atom (4 3 4.4))
[4.4]
!(min-atom (3 5 2.9))
[2.9]
Documentation and tests are also added.
> Min max size functions added

- python/hyperon/atoms.py
Previous implementation hides conversion exception thrown from get_object() method. It makes debug difficult. Handle attempts to call get_object() on non-grounded atoms by separate condition. All other errors are thrown to the upper stack frames.
> Show grounded atom conversion exceptions if any

- c/src/atom.rs
- c/src/metta.rs
- lib/src/atom/mod.rs
- lib/src/common/collections.rs
- lib/src/metta/interpreter_minimal.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/builtin_mods/catalog_mods.rs
- lib/src/metta/runner/stdlib_minimal.rs
- lib/src/metta/types.rs
- lib/tests/metta.rs
- lib/tests/types.rs
This is small refactoring of the `ExpressionAtom` in order to allow making constant expressions like `UNIT_ATOM` and `UNIT_TYPE`.
> Allow instantiating constant expression atoms in Rust code

- lib/src/space/grounding.rs
> Remove only one instance of the duplicated atom

- lib/src/atom/serial.rs
- lib/src/metta/runner/arithmetics.rs
- lib/src/metta/runner/stdlib_minimal.rs
- lib/src/metta/runner/string.rs
@DaddyWesker should simplify `Number` conversion for stdlib.
> Improve primitive conversion code

- lib/src/metta/interpreter_minimal.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/stdlib_minimal.metta
Fixes #803 Add additional evalc operation which can evaluate passed atom using passed space. Use evalc to implement metta function. Add unit test for the case.
> Fix metta function to make evaluation using the passed context space

- lib/src/metta/runner/stdlib/stdlib.metta
- repl/src/main.rs
Fixes #815 
`!(help!)` shows the list of stdlib functions. Add REPL banner to inform user about website and `!(help!)`.
> Calling help! without parameters shows list of stdlib functions

- c/src/space.rs
- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/stdlib/module.rs
- lib/src/metta/runner/stdlib/space.rs
- lib/src/space/grounding.rs
- lib/src/space/mod.rs
- lib/src/space/module.rs
- python/tests/scripts/f1_imports.metta
This PR is replacement of #776 without issue which were caused by old interpreter implementation. New commits start from https://github.com/trueagi-io/hyperon-experimental/commit/4277146f621100f3f408bb3bfae724617a57a226
In this PR `ModuleSpace` is introduced which keeps main space and its dependencies separately. This allows querying them separately and when dependent space is queried it doesn't queried recursively. Thus all transitive dependencies are queried only once from the top level space.
For example if we have space `A` which imports space `B` and `C` and `D` is imported from `B` and `C` then `A` contains `B`, `C` and `D` as dependencies in a separate collection. Query to `A` goes through its atoms first then goes to `B`, `C` and `D` but dependencies of these spaces are not …
> Don't copy imported module to filter out its dependencies

- lib/Cargo.toml
- lib/src/atom/mod.rs
- lib/src/common/assert.rs
- lib/src/common/collections.rs
- lib/src/metta/runner/stdlib/debug.rs
- repl/Cargo.toml
- repl/src/metta_shim.rs
Use `Display` to show atoms in REPL and logs. Use `Debug` in unit test implementations.
@DaddyWesker FYI
> Separate Debug and Display trait implementations for Atom

- lib/src/metta/runner/stdlib/debug.rs
Evaluating second argument before calling trace! leads to unexpected sequence of traces. Making type of the second argument Atom means argument is evaluated after trace! prints the first argument.
> Return second argument of trace! without evaluation

- lib/src/metta/runner/mod.rs
- lib/src/space/module.rs
- python/tests/test_metta.py
Fix #834. Root cause is that top module space is different from space which is passed to the `Metta` constructor. Module space additionally wrapped by `ModuleSpace` which contains dependencies and know how to work with them. `evaluate_atom` used original space instead of modules space it is why it cannot use dependencies. Fix is to get top module space instead.
> Fix evaluate atom

- lib/src/metta/runner/environment.rs
- lib/src/metta/runner/str.rs
> Return strip_quotes to prevent unnecessary folder creation

- python/tests/test_grounded_type.py
See https://github.com/trueagi-io/hyperon-experimental/issues/841#issuecomment-2624320069
> Fix repr unit test in Python to check escaping

- lib/src/metta/types.rs
First step to optimize type checker. It should improve performance in complex cases in about 6 times (see #850).
PR changes code to calculate children types only once. Also it fixes but in type checker: when one of the arguments is checked by meta type all other arguments are not checked. This bug probably not visible in real cases because interpreter has other type-checking algorithm.
> Optimize type checking

- .github/workflows/ci-auto.yml
- .github/workflows/ci-manual.yml
- .github/workflows/common.yml
- Dockerfile
- README.md
- python/install-hyperonc.sh
- python/pyproject.toml
> Windows tests added to github workflow

- lib/src/atom/serial.rs
- lib/src/metta/runner/stdlib/atom.rs
Fix for the case:
```
(number 1)
(number 2)
(number 3)
!(max-atom (collapse (match &self (number $x) $x)))
```
which returns panic:
```
thread 'main' panicked at lib/src/atom/serial.rs:65:56:
ConvertingSerializer is not expected returning error: NotSupported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Return normal error instead of panic Allow call chaining for the argument of the `max-atom` and `min-atom`.
> Fix max atom

- lib/src/metta/runner/pkg_mgmt/git_catalog.rs
Tiny doc change.  No code changed.
> Improving docs to clarify purpose of `GitCatalog::new_without_source_repo`

- lib/src/metta/runner/environment.rs
- lib/src/metta/runner/pkg_mgmt/git_catalog.rs
This feature makes it possible to configure an embedded MeTTa installation to always pull the latest updated modules from a remote server (as opposed to when the user performs an update command)
It also makes it easier to test functionality that performs caching in the file system (mainly git fetch), without supplying a complete config, or falling back to the default config.
The default behavior remains exactly the same.
> Changes so GitCatalog can be used by itself, without a LocalCatalog

- lib/src/metta/runner/stdlib/atom.rs
- lib/src/metta/runner/stdlib/mod.rs
- lib/src/metta/runner/stdlib/stdlib.metta
So, new pr. I've added add-reducts function after discussing with @Necr0x0Der which uses foldl-atom in it's core. Usage:
```
!(bind! &newspace (new-space))
!(add-reducts &newspace ((k1 v1) (k2 v2) (k3 v3)))
!(assertEqual
(match &newspace (k1 $v) $v)
v1)
```
I've also added doc and tests (@vsbogd please check if tests are in right place, I'm not sure). 
Strange thing I've noticed when I was writing tests. This one works:
```
!(chain (eval (new-space)) $newspace
(let $f (add-reducts $newspace ((k1 v1) (k2 v2) (k3 v3)))
(assertEqual
(match $newspace (k1 $v) $v)
v1)))
```
This one - not:
```
!(chain (eval (new-space)) $newspace
(chain (eval (add-reducts $newspace ((k1 v1) (k2 v2) (k3 v3)))) $f
(assertEqual
(match $newspace (k1 $v) $v)
v1)))
```
I can't quite understand why...
> Add add-reducts

- lib/src/atom/mod.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/stdlib/core.rs
- lib/src/metta/runner/stdlib/debug.rs
- lib/src/metta/runner/stdlib/mod.rs
- lib/src/metta/runner/stdlib/stdlib.metta
Return error if stack depth limit is reached.
Current implementation has the following pecularities:
1. The stack depth is calculated in terms of the minimal MeTTa instructions not MeTTa instructions thus the actual stack depth can be bigger than expected as minimal MeTTa instructions are more detailed.
2. Execution is interrupted and returns error only on the next MeTTa function call. This is required to correctly return error from the
minimal MeTTa stack when MeTTa program is executed.
3. Case/capture/superpose/collapse/assert operations call interpreter from the interpreter stack and it leads to the creation of the new stack. Thus if `case` (or other similar operation) is used the limit counter is started from the beginning for the nested expression. In stack where `case` calls `case` …
> Limit recursion depth

- lib/src/atom/gnd.rs
- lib/src/atom/mod.rs
- lib/src/metta/runner/builtin_mods/catalog_mods.rs
- lib/src/metta/runner/builtin_mods/mod.rs
- lib/src/metta/runner/builtin_mods/skel.metta
- lib/src/metta/runner/builtin_mods/skel.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/stdlib/atom.rs
- lib/src/metta/runner/stdlib/core.rs
- lib/src/metta/runner/stdlib/debug.rs
- lib/src/metta/runner/stdlib/math.rs
- lib/src/metta/runner/stdlib/mod.rs
- lib/src/metta/runner/stdlib/random.rs
Built-in module named "skel" is added as an example of the native module. One should import module before using it, for example:
```
!(import! &self skel)
!(skel-swap-pair (Pair a b))
!(skel-swap-pair-native (Pair a b))
```
Also the `GroundedFunctionAtom` structure is added to easily add new grounded operations into Rust libraries. It allows wrapping functions, lambdas or structures which implement `GroundedFunction` trait. For lambdas and functions with specific signature this trait is implemented automatically.
This PR fixes incorrect `catalog` module behavior which was introduced by https://github.com/trueagi-io/hyperon-experimental/pull/894 (see https://github.com/trueagi-io/hyperon-experimental/pull/913/commits/22066446a055602edeaa6559934d89d65d5476da and …
> Add builtin module example

- c/src/lib.rs
- c/src/metta.rs
- c/src/module.rs
- c/src/util.rs
- c/tests/check_runner.c
- c/tests/util.c
- lib/src/metta/runner/builtin_mods/catalog_mods.rs
- lib/src/metta/runner/builtin_mods/skel.rs
- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/stdlib/mod.rs
- lib/src/metta/text.rs
- python/hyperon/ext.py
- python/hyperon/module.py
- python/hyperon/runner.py
- python/hyperon/stdlib.py
- python/hyperonpy.cpp
- python/tests/test_modules.py
This PR is a followup after #894. It adds `ModuleLoader::load_tokens` method and uses it to export tokens from module A into importing module B. Thus only exported tokens are copied into the importing module. This change is simple on a Rust side but required significant work on Python side as fully functional `ModuleLoader` implementation is required there.
On core library side `ModuleLoader::load_tokens` method is added and implemented for `corelib` and built-in modules. It is used to export tokens into importing module and old `own_tokenizer` is removed.
On `hyperonc` side new module `module.rs` is added. Most of the module handing code and structure are moved there. New `module_loader_t` is implemented which allows implementing `ModuleLoader` interface from a C program. …
> Allow direct tokens loading into importing module

- c/src/metta.rs
- c/src/space.rs
- lib/benches/interpreter_minimal.rs
- lib/benches/type.rs
- lib/src/common/test_utils.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/runner/builtin_mods/catalog_mods.rs
- lib/src/metta/runner/builtin_mods/skel.rs
- lib/src/metta/runner/environment.rs
- lib/src/metta/runner/mod.rs
- lib/src/metta/runner/modules/mod.rs
- lib/src/metta/runner/pkg_mgmt/catalog.rs
- lib/src/metta/runner/stdlib/atom.rs
- lib/src/metta/runner/stdlib/core.rs
- lib/src/metta/runner/stdlib/debug.rs
- lib/src/metta/runner/stdlib/mod.rs
- lib/src/metta/runner/stdlib/space.rs
- lib/src/metta/types.rs
- lib/src/space/grounding/mod.rs
- lib/src/space/mod.rs
- lib/src/space/module.rs
Before I tried to pass the instance of `Space` or `SpaceMut` into interpreter and other functions but it doesn't work for all use-cases. For example I cannot get the space and wrap it into the atom inside interpreter. Thus I decided to use `Space` and `SpaceMut` only as an API for the new kind of space implementers. After space is instantiated it should be wrapped into `DynSpace` and then passed via code.
This change simplifies `Space` and `SpaceMut` API, removes some unnecessary `Space` implementations and significantly simplifies `DynSpace` as it should not implement nor `Space` or `SpaceMut` anymore.
> Use DynSpace everywhere as the only way to pass some space through the code

- lib/src/metta/runner/stdlib/stdlib.metta
Change return type to %Undefined% to evaluate returned result. Changing return type to variable fails tests. Expression is not appropriate type as result is superposed and it can have non expression type.
Fixes part of the #924, thanks @Bitseat for finding a root cause.
> Fix union, subtraction, intersection, unique

- c/src/metta.rs
- lib/src/common/collections.rs
- lib/src/metta/interpreter.rs
- lib/src/metta/mod.rs
- lib/src/metta/runner/stdlib/atom.rs
- lib/src/metta/runner/stdlib/core.rs
- lib/src/metta/runner/stdlib/debug.rs
- lib/src/metta/runner/stdlib/mod.rs
- lib/src/metta/runner/stdlib/module.rs
- lib/src/metta/runner/stdlib/space.rs
- lib/src/metta/runner/stdlib/stdlib.metta
- lib/src/space/mod.rs
Add `context-space` operation to get current interpreter space and implement collapse on the top of it.
Use new collapse implementation in `assert...` implementations.
Fixes #924 Opens road to implement #900 
@Bitseat FYI
> Implement assert in metta

- lib/src/space/grounding/mod.rs
- lib/tests/space.rs
It is not needed anymore after migration to using DynSpace everywhere in code.
> Remove Grounded trait implementation from GroundingSpace

- hyperon-atom/src/serial.rs
- lib/src/metta/runner/number.rs
Fixes #949 
In Rust `1.0 as u64` converts float into an integer by rounding. As a result `1` and `1.0` has the same hash when they are hashed by serializer implementation for `DefaultHasher`. This commit uses `transmute` to convert binary representation of the `f64` to `i64` and thus makes hashes different.
> Make integer and float have different hash

- lib/src/metta/runner/stdlib/stdlib.metta
- lib/tests/test_stdlib.metta
Fix proposal for #920 
After allowing using Atom meta-type to return an atom without evaluation, it is possible to implement a new quoting mechanism. (: noeval (-> Atom Atom)) function (former id) is used to return atom without evaluation. (: id (-> $t $t)) function is used to force evaluation of the atom.
This PR changes type of the id function from (-> Atom Atom) to (-> $t $t) as it is more logical. And introduces new noeval function with (-> Atom Atom) signature to implement new quoting mechanism.
> Introduce new quoting using noeval/id functions

- lib/src/metta/interpreter.rs
- lib/src/metta/runner/stdlib/atom.rs
- lib/src/metta/runner/stdlib/stdlib.metta
1. Fix eval/evalc/function return type. Changing unify/chain breaks too many programs.
2. Return Empty from minimal MeTTa interpreter on a final step
> Fix minimal MeTTa interpreter behavior

- lib/src/metta/runner/builtin_mods/random.rs
- lib/src/metta/runner/stdlib/atom.rs
- lib/src/metta/runner/stdlib/debug.rs
- lib/src/metta/runner/stdlib/math.rs
- lib/src/metta/runner/stdlib/mod.rs
Re-make of [PR](https://github.com/trueagi-io/hyperon-experimental/pull/966) after Vitaly's review. Eval's either removed from tests or changed from chain+eval to let.
> Eval cleaning

- lib/src/metta/runner/stdlib/debug.rs
- lib/src/metta/runner/stdlib/stdlib.metta
- lib/tests/test_stdlib.metta
So, I've added `assert` as @ngeiswei  asked [here](https://github.com/trueagi-io/hyperon-experimental/issues/900) , please check if it is what you've asked.
I've also added some asserts with custom messages as @Necr0x0Der asked [here](https://github.com/trueagi-io/hyperon-experimental/issues/861) . Please also check if it is fine with you. 
One thing about asserts with custom message. Regular assert will stop program from further interpretation on failure, but -Msg asserts won't. I'm not sure about this behavior.  As an alternative, instead of just outputting custom message it could be wrapped into Error like regular output of assert. So some 
`!(assertEqualMsg (+ 1 2) 4 "Test message")` will output `(Error (assertEqualMsg (+ 1 2) 4 "Test message") "Test message")` instead of just ("Test …
> assert and asserts with messages added

- hyperon-atom/src/lib.rs
- hyperon-atom/src/serial.rs
- lib/src/metta/runner/bool.rs
- lib/src/metta/runner/builtin_mods/json.rs
- lib/src/metta/runner/number.rs
- lib/src/metta/runner/stdlib/debug.rs
- lib/src/metta/runner/stdlib/string.rs
- lib/src/metta/runner/str.rs
- repl/src/metta_shim.rs
Check the type of the grounded atom during its conversion into a Rust value. This fixes `format-args` accepts non string values as a first argument mentioned in #978.
> Add string conversion

- lib/src/metta/runner/stdlib/core.rs
- lib/src/metta/runner/stdlib/stdlib.metta
- lib/tests/test_stdlib.metta
Sealed was reworked to accept list of ignored variables instead of variables to be sealed. Using sealed, https://github.com/trueagi-io/hyperon-experimental/issues/857 was fixed. Also code by Zarathustra Goertzel from Mattermost works now. I've also added two tests to test_stdlib.metta to check those issues. And I've returned if-decons.
PR was reopened due to update to the latest main gone wrong.
> sealed update, foldl-, map- and filter-atom updated

- lib/src/metta/mod.rs
Fix behavior when rust panic was thrown on importing of metta script which contains assert which throws an error. 
Before:
```
!(import! &self assertErr)
[2025-08-08T05:55:02Z INFO  hyperon::metta::runner::pkg_mgmt::catalog] Found module: "assertErr" inside "Dir \"/home/daddywesker/SingularityNet/Metta/dw_fork/hyperon-experimental\""
[2025-08-08T05:55:02Z INFO  hyperon::metta::runner::pkg_mgmt::catalog] Preparing to load module: 'assertErr' as 'top:assertErr'
thread 'main' panicked at lib/src/metta/mod.rs:86:62:
Atom is not error expression: "Atom is not a SymbolAtom"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After:
```
!(import! &self assertErr)
[2025-08-08T06:52:49Z INFO  hyperon::metta::runner::pkg_mgmt::catalog] Found module: "assertErr" inside …
```
> change behavior of atom_error_message fun

- .github/workflows/common.yml
Quickfix for nightly CI job extracted from #1006
> Install Protobuf in CI container for MacOSX and Windows

- .github/workflows/ci-manual.yml
- .github/workflows/ci-nightly.yml
- .github/workflows/das-tests.yml
Allow passing Python environment version. Fix `das-cli` setup to use this version and virtual environment.
@arturgontijo I have some questions about it:
1. job fails with Python 3.8 (https://github.com/vsbogd/hyperon-experimental/actions/runs/17214743919) what is the minimal version of Python supported by DAS cli?
2. DAS cli requires manual requirements installation (`python3 -m pip install -r requirements.txt`) (see https://github.com/vsbogd/hyperon-experimental/actions/runs/17214573397/job/48834855776) but one would expect `python3 -m pip install .` should be enough.
3. Job still fails after all fixes (https://github.com/vsbogd/hyperon-experimental/actions/runs/17214801060/job/48835629376) not sure why
4. I think the approach with the separate job is not efficient, it requires …
> Fix DAS tests job

- hyperon-space/src/index/mod.rs
- hyperon-space/src/index/trie.rs
PR changes the format of the key of the atom index trie. Before expressions are represented in a form: `START_EXPR <atom>* END_EXPR`. After this PR expressions are represented in a form: `START_EXPR(size) <atom>{size}`. This allows keeping expressions of different length in different branches of the trie. And thus prevents for example comparing function atoms for function calls with different arity (for instance `(foo)` and `(foo arg)`) like happens in issue https://github.com/trueagi-io/hyperon-experimental/issues/997. This change makes atomspace a bit more compact (smaller number of tokens) and search a bit faster (separate results earlier).
The change adds a restriction on a maximum expression size. In this PR it is set to 2^10 items. There is no technical restriction to make this …
> Prefix expressions with size in atomspace index to recognize them faster

- .github/workflows/common.yml
- Dockerfile
- README.md
- python/install-hyperonc.sh
- python/pyproject.toml
Fixes issue in nightly build on MacOSX 15 https://github.com/trueagi-io/hyperon-experimental/actions/runs/17366907632/job/49298632531. Test run: https://github.com/vsbogd/hyperon-experimental/actions/runs/17368830784/job/49300388057.
> Upgrade Conan version to 2.19.1 to fix MacOSX 15 build

- lib/src/metta/interpreter.rs
- lib/src/metta/runner/builtin_mods/fileio.rs
- lib/src/metta/runner/stdlib/math.rs
Fixes return type checking when function is called from the body of another function. It also for free stops evaluation in a case when `Atom` or `Expression` is returned. 
As at the moment according to the specification only `Atom` stops evaluation case with expression is handled by special condition in code. Old implementation from https://github.com/trueagi-io/hyperon-experimental/commit/99dd9911f85cbbd76acbc8390a54d35e2210d42c is removed by reverting this commit.
Some standard library changes are required because `file-read-exact!`, `isnan-math` and `isinf-math` has incorrect return types.
Better review each commit.
> Fix return type check
